---
- name: Install PostgreSQL
  apt:
    name:
      - postgresql
      - postgresql-contrib
    state: present
    update_cache: yes


- name: Enable PostgreSQL
  systemd:
    name: postgresql
    enabled: yes
    state: started


- name: Allow remote PostgreSQL
  lineinfile:
    path: /etc/postgresql/*/main/postgresql.conf
    regexp: '^#?listen_addresses'
    line: "listen_addresses = '*'"


- name: Restart PostgreSQL
  systemd:
    name: postgresql
    state: restarted
