---
- name: Install Redis
  apt:
    name: redis-server
    state: present
    update_cache: yes


- name: Enable Redis
  systemd:
    name: redis-server
    enabled: yes
    state: started


- name: Configure Redis bind
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind'
    line: 'bind 0.0.0.0'


- name: Restart Redis
  systemd:
    name: redis-server
    state: restarted
